server:
  port: 8888
spring:
  application:
    name: API-Gateway
  cloud:
    gateway:
      routes:
        - id: User-service
          uri: http://user-service  # 쿠버네티스 서비스 이름
          predicates:
            - Path=/user/**
          filters:
            - StripPrefix=1
        - id: Attendance-service
          uri: http://attendance-service  # 쿠버네티스 서비스 이름
          predicates:
            - Path=/attendance/**
          filters:
            - StripPrefix=1

    discovery:
      enabled: false

logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.cloud.loadbalancer: TRACE
    org.springframework.web.reactive.function.client: TRACE
    reactor.netty.http.client: DEBUG
    org.springframework.cloud.gateway.filter.LoadBalancerClientFilter: TRACE
    org.springframework.cloud.gateway.handler.RoutePredicateHandlerMapping: TRACE