server:
  port: 8888
spring:
  jmx:
    enabled: false
  application:
    name: API-Gateway
  cloud:
    config:
      enabled: false
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: finance-service
          uri: http://finance.msanew:8080
          predicates:
            - Path=/finance/**
          filters:
            - StripPrefix=1

        - id: User-service
          uri: http://user.msanew:7070
          predicates:
            - Path=/user/**
          filters:
            - StripPrefix=1

        - id: Attendance-service
          uri: http://attendance.msanew:6060
          predicates:
            - Path=/attendance/**
          filters:
            - StripPrefix=1
    discovery:
      enabled: true
      client:
        aws:
          discovery:
            enabled: true

logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.cloud.loadbalancer: TRACE
    org.springframework.web.reactive.function.client: TRACE
    reactor.netty.http.client: DEBUG
    org.springframework.cloud.gateway.filter.LoadBalancerClientFilter: TRACE
    org.springframework.cloud.gateway.handler.RoutePredicateHandlerMapping: TRACE