server:
  port: 6060
spring:
  jackson:
    time-zone: Asia/Seoul
  mail:
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}

  application:
    name: Attendance
  datasource:
    url: jdbc:mysql://${DB_URL}?serverTimezone=Asia/Seoul&useLegacyDatetimeCode=false&cacheDefaultTimezone=false
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: false   # SQL 보기 좋게 포맷팅
        jdbc:
          time_zone: Asia/Seoul  # 여기에 Hibernate 시간대 설정 추가
  cloud:
    gcp:
      enabled: true
      storage:
        bucket: fisa_final_project
        project-id: woven-coral-441407-d3
  batch:
    jdbc:
      initialize-schema: always
      table-prefix: BATCH_
    job:
      enabled: false