name: CI/CD Pipeline

on:
  push:
    branches:
      - k8s

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    
    - name: Grant execute permission for gradlew
      run: chmod +x API-Gateway/gradlew
    
    - name: Build with Gradle
      run: |
        cd API-Gateway
        ./gradlew build
    
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    
    - name: Build and push Docker image
      uses: docker/build-push-action@v3
      with:
        context: ./API-Gateway
        push: true
        tags: jihyukdocker/api-gw:v1.0.1
    
    - name: Update k8s Deployment
      run: |
        # 이미지 태그를 동적으로 deployment yaml에 적용
        sed -i "s|image: jihyukdocker/api-gw:.*|image: jihyukdocker/api-gw:v1.0.1|" k8s/apigw.yaml
        
        # 변경된 파일 커밋 및 푸시
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add k8s/api-gateway-deployment.yaml
        git commit -m "Update API Gateway image to v1.0.1"
        git push
